name: "Signing Windows Artifacts"
description: "Signing Windows Artifacts"

inputs:
  unsigned-path:
    description: "Path to the unsigned artifact"
    required: true

  signed-path:
    description: "Path to the signed artifact"
    required: true

runs:
  using: "composite"
  steps:
    - name: upload-unsigned-artifact
      id: upload-unsigned-artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ inputs.unsigned-path }}

    - id: optional_step_id
      uses: signpath/github-action-submit-signing-request@v1.1
      with:
        api-token: "${{ secrets.SIGNPATH_API_TOKEN }}"
        organization-id: "${{ vars.SIGNPATH_ORGANIZATION_ID }}"
        project-slug: "pactus"
        signing-policy-slug: "{{ vars.SIGNPATH_SIGNING_POLICY_SLUG }}"
        github-artifact-id: "${{ steps.upload-unsigned-artifact.outputs.artifact-id }}"
        wait-for-completion: true
        output-artifact-directory: "${{ inputs.signed-path }}"
