name: Build and Test GUI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-gui:
    runs-on: ${{ matrix.name }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    strategy:
      matrix:
        # Default values for `defaults.run.shell`
        # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell
        include:
          - name: ubuntu-latest
            shell: "bash -e {0}"
            cache-path: |
              ~/go/pkg/mod
              ~/.cache/go-build
          - name: macos-latest
            shell: "bash -e {0}"
            cache-path: |
              ~/go/pkg/mod
              ~/Library/Caches/go-build
          - name: windows-latest
            shell: "msys2 {0}"
            cache-path: |
              ~/go/pkg/mod
              ~/.cache/go-build

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - uses: actions/cache@v4
        with:
          path: ${{ matrix.cache-path }}
          key: ${{ matrix.name }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.name }}-go-

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux' && steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libcairo2-dev libglib2.0-dev

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS' && steps.cache.outputs.cache-hit != 'true'
        run: brew install gtk+3

      - name: Setup MSYS2 and Dependencies (Windows)
        if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            git
            make
            glib2-devel
            mingw-w64-x86_64-go
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config

      - name: Patch pkgconfig (Windows)
        if: runner.os == 'Windows' && steps.cache.outputs.cache-hit != 'true'
        run: |
          sed -i -e 's/-Wl,-luuid/-luuid/g' /mingw64/lib/pkgconfig/gdk-3.0.pc

      - name: Install and Cache GTK
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          go install github.com/gotk3/gotk3/gtk
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62

      - name: Build the GUI binary
        run: make build_gui

      - name: Lint check (Linux only)
        if: runner.os == 'Linux'
        run: |
          BUILD_TAG=gtk make check
