name: "Release GUI Windows Artifacts"
permissions:
  contents: write

on:
  push:
    tags: ["v*"]

jobs:
  release-gui-windows:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        name: [windows_amd64]
        include:
          - name: windows_amd64
            runner: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git
            make
            p7zip
            glib2-devel
            mingw-w64-x86_64-go
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config

      - name: Get Version
        id: get_version
        run: |
          VERSION="$(echo `git -C . describe --abbrev=0 --tags` | sed 's/^.//')" # "v1.2.3" -> "1.2.3"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Binaries
        run: bash ./.github/releasers/releaser_gui_windows_build.sh

      - name: Sign Pactus Daemon
        uses: ./.github/actions/windows-signing
        with:
            signpath-api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
            signpath-signing-policy-slug: ${{ vars.SIGNPATH_SIGNING_POLICY_SLUG }}
            artifact-name: pactus-daemon

      - name: Sign Pactus Wallet
        uses: ./.github/actions/windows-signing
        with:
            signpath-api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
            signpath-signing-policy-slug: ${{ vars.SIGNPATH_SIGNING_POLICY_SLUG }}
            artifact-name: pactus-wallet

      - name: Sign Pactus Shell
        uses: ./.github/actions/windows-signing
        with:
            signpath-api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
            signpath-signing-policy-slug: ${{ vars.SIGNPATH_SIGNING_POLICY_SLUG }}
            artifact-name: pactus-shell

      - name: Sign Pactus GUI
        uses: ./.github/actions/windows-signing
        with:
            signpath-api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
            signpath-signing-policy-slug: ${{ vars.SIGNPATH_SIGNING_POLICY_SLUG }}
            artifact-name: pactus-gui

      - name: Build Installer
        run: bash ./.github/releasers/releaser_gui_windows_installer.sh

      - name: Sign Installer
        uses: ./.github/actions/windows-signing
        with:
            signpath-api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
            signpath-signing-policy-slug: ${{ vars.SIGNPATH_SIGNING_POLICY_SLUG }}
            artifact-name: pactus-gui_${{ steps.get_version.outputs.VERSION }}_${{ matrix.name }}_installer

      - name: Move Installer to Root
        run: mv ./build/signed/pactus-gui_*_installer.exe .

      - name: Calculate sha256sum
        run: sha256sum pactus-gui_*.zip pactus-gui_*_installer.exe > checksum-gui-${{ matrix.name }}.txt

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-gui-${{ matrix.name }}
          path: checksum-gui-${{ matrix.name }}.txt

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pactus-gui_*.zip
            pactus-gui_*_installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
