name: Releaser
permissions:
  # https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions
  contents: write

on:
  push:
    tags: ["v*"]

jobs:


  ########################################
  build-gui-macos:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        name: [macos-amd64]
        include:
          - name: macos-amd64
            runner: macos-15-intel
            lib_home: /usr/local

    env:
      LIB_HOME: ${{ matrix.lib_home }}

    steps:
      - uses: actions/checkout@v5

      - name: Install Dependencies
        run: brew install gtk+3 librsvg create-dmg coreutils gdk-pixbuf glib-networking pkg-config

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"

      - name: Create release files
        run: bash ./.github/releasers/releaser_gui_macos.sh

      - name: Calculate sha256sum
        run: sha256sum pactus-*.dmg pactus-*.tar.gz > checksum-${{ matrix.name }}.txt

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-${{ matrix.name }}
          path: checksum-${{ matrix.name }}.txt

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pactus-*.dmg
            pactus-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  ########################################
  checksums:
    needs:
      [
        build-cli,
        build-gui-linux,
        build-gui-macos,
        build-gui-windows,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Download checksum artifacts
        uses: actions/download-artifact@v4
        with:
          path: checksums

      - name: Combine checksums
        run: |
          cat checksums/*/*.txt > SHA256SUMS
          cat SHA256SUMS

      - name: Upload SHA256SUMS as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: sha256sums
          path: SHA256SUMS

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: SHA256SUMS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ########################################
  cosign:
    needs: [checksums]
    runs-on: ubuntu-latest
    steps:
      - name: Download SHA256SUMS artifact
        uses: actions/download-artifact@v4
        with:
          name: sha256sums

      - uses: sigstore/cosign-installer@v3

      - name: Sign Checksum
        run: cosign sign-blob --yes --key env://COSIGN_PRIVATE_KEY SHA256SUMS > SHA256SUMS.sig
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: SHA256SUMS.sig

  ########################################
  downloader:
    needs: [cosign]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Create Downloader file
        run: |
          VERSION="$(echo `git -C . describe --abbrev=0 --tags` | sed 's/^.//')" # "v1.2.3" -> "1.2.3"
          echo ${VERSION}
          sed -i "s/__VERSION__/${VERSION}/g" .github/releasers/pactus_downloader.sh

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: .github/releasers/pactus_downloader.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
