name: "Release CLI Artifacts"
permissions:
  contents: write

on:
  push:
    tags: ["v*"]

jobs:
  release-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install zip

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Create release files
        run: bash ./.github/releasers/releaser_cli.sh

      - name: Calculate sha256sum
        run: sha256sum pactus-*.zip pactus-*tar.gz > checksum-cli.txt

      - name: Upload checksum artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-cli
          path: checksum-cli.txt

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pactus-*.zip
            pactus-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
